name: publish-snapshot
on:
  push:
    branches: [dev]
jobs:
  publish-to-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
      - uses: actions/checkout@v3
      - name: Setting up Java 17
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - run: chmod +x gradlew
      - name: Publish with Gradle
      - run: ./gradlew clean jar publish -Pmaven-user=${{ secrets.MAVEN_REPO_USER }} -Pmaven-pass=${{ secrets.MAVEN_PASS }} -PisSnapshot=true


